apiVersion: v1
kind: Secret
metadata:
  name: colorbot-secret
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false   
  labels:
    {{- include "colorbot.labels" . | nindent 4 }}
type: Opaque
data: 
  telegram_bot_token: {{ randAlphaNum 24 | b64enc | quote }}
  colorbot_secret: {{ randAlphaNum 24 | b64enc | quote }}
  owner_ids: {{ randAlphaNum 24 | b64enc | quote }}
  database_url: {{ randAlphaNum 24 | b64enc | quote }}
  default_lang: {{ randAlphaNum 24 | b64enc | quote }}